[build]
  publish = "public"
  command = "npm run clean && npm run build"

[template.environment]
  ASTRA_DB_APPLICATION_TOKEN = "Your Astra DB Application Token"
  ASTRA_DB_KEYSPACE = "Your Astra DB Keyspace"
  ASTRA_DB_REGION = "Your Astra DB Region"
  ASTRA_DB_ID = "Your Astra DB ID"
